package com.whale.generator.netty.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto



public final class Mobile {
  private Mobile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MobilePhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MobilePhone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string brand = 1;</code>
     * @return The brand.
     */
    java.lang.String getBrand();
    /**
     * <code>string brand = 1;</code>
     * @return The bytes for brand.
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string hardware = 2;</code>
     * @return The hardware.
     */
    java.lang.String getHardware();
    /**
     * <code>string hardware = 2;</code>
     * @return The bytes for hardware.
     */
    com.google.protobuf.ByteString
        getHardwareBytes();

    /**
     * <code>string software = 3;</code>
     * @return The software.
     */
    java.lang.String getSoftware();
    /**
     * <code>string software = 3;</code>
     * @return The bytes for software.
     */
    com.google.protobuf.ByteString
        getSoftwareBytes();
  }
  /**
   * Protobuf type {@code MobilePhone}
   */
  public static final class MobilePhone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MobilePhone)
      MobilePhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MobilePhone.newBuilder() to construct.
    private MobilePhone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MobilePhone() {
      brand_ = "";
      hardware_ = "";
      software_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MobilePhone();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MobilePhone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              hardware_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              software_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whale.generator.netty.proto.Mobile.internal_static_MobilePhone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whale.generator.netty.proto.Mobile.internal_static_MobilePhone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whale.generator.netty.proto.Mobile.MobilePhone.class, com.whale.generator.netty.proto.Mobile.MobilePhone.Builder.class);
    }

    public static final int BRAND_FIELD_NUMBER = 1;
    private volatile java.lang.Object brand_;
    /**
     * <code>string brand = 1;</code>
     * @return The brand.
     */
    @java.lang.Override
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 1;</code>
     * @return The bytes for brand.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HARDWARE_FIELD_NUMBER = 2;
    private volatile java.lang.Object hardware_;
    /**
     * <code>string hardware = 2;</code>
     * @return The hardware.
     */
    @java.lang.Override
    public java.lang.String getHardware() {
      java.lang.Object ref = hardware_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hardware_ = s;
        return s;
      }
    }
    /**
     * <code>string hardware = 2;</code>
     * @return The bytes for hardware.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHardwareBytes() {
      java.lang.Object ref = hardware_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hardware_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOFTWARE_FIELD_NUMBER = 3;
    private volatile java.lang.Object software_;
    /**
     * <code>string software = 3;</code>
     * @return The software.
     */
    @java.lang.Override
    public java.lang.String getSoftware() {
      java.lang.Object ref = software_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        software_ = s;
        return s;
      }
    }
    /**
     * <code>string software = 3;</code>
     * @return The bytes for software.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSoftwareBytes() {
      java.lang.Object ref = software_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        software_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
      }
      if (!getHardwareBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hardware_);
      }
      if (!getSoftwareBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, software_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
      }
      if (!getHardwareBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hardware_);
      }
      if (!getSoftwareBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, software_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.whale.generator.netty.proto.Mobile.MobilePhone)) {
        return super.equals(obj);
      }
      com.whale.generator.netty.proto.Mobile.MobilePhone other = (com.whale.generator.netty.proto.Mobile.MobilePhone) obj;

      if (!getBrand()
          .equals(other.getBrand())) return false;
      if (!getHardware()
          .equals(other.getHardware())) return false;
      if (!getSoftware()
          .equals(other.getSoftware())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + HARDWARE_FIELD_NUMBER;
      hash = (53 * hash) + getHardware().hashCode();
      hash = (37 * hash) + SOFTWARE_FIELD_NUMBER;
      hash = (53 * hash) + getSoftware().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.proto.Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.whale.generator.netty.proto.Mobile.MobilePhone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MobilePhone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MobilePhone)
        com.whale.generator.netty.proto.Mobile.MobilePhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whale.generator.netty.proto.Mobile.internal_static_MobilePhone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whale.generator.netty.proto.Mobile.internal_static_MobilePhone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whale.generator.netty.proto.Mobile.MobilePhone.class, com.whale.generator.netty.proto.Mobile.MobilePhone.Builder.class);
      }

      // Construct using com.whale.generator.netty.proto.Mobile.MobilePhone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        brand_ = "";

        hardware_ = "";

        software_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whale.generator.netty.proto.Mobile.internal_static_MobilePhone_descriptor;
      }

      @java.lang.Override
      public com.whale.generator.netty.proto.Mobile.MobilePhone getDefaultInstanceForType() {
        return com.whale.generator.netty.proto.Mobile.MobilePhone.getDefaultInstance();
      }

      @java.lang.Override
      public com.whale.generator.netty.proto.Mobile.MobilePhone build() {
        com.whale.generator.netty.proto.Mobile.MobilePhone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.whale.generator.netty.proto.Mobile.MobilePhone buildPartial() {
        com.whale.generator.netty.proto.Mobile.MobilePhone result = new com.whale.generator.netty.proto.Mobile.MobilePhone(this);
        result.brand_ = brand_;
        result.hardware_ = hardware_;
        result.software_ = software_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whale.generator.netty.proto.Mobile.MobilePhone) {
          return mergeFrom((com.whale.generator.netty.proto.Mobile.MobilePhone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whale.generator.netty.proto.Mobile.MobilePhone other) {
        if (other == com.whale.generator.netty.proto.Mobile.MobilePhone.getDefaultInstance()) return this;
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getHardware().isEmpty()) {
          hardware_ = other.hardware_;
          onChanged();
        }
        if (!other.getSoftware().isEmpty()) {
          software_ = other.software_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whale.generator.netty.proto.Mobile.MobilePhone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whale.generator.netty.proto.Mobile.MobilePhone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>string brand = 1;</code>
       * @return The brand.
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       * @return The bytes for brand.
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       * @param value The brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrand() {

        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       * @param value The bytes for brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        brand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hardware_ = "";
      /**
       * <code>string hardware = 2;</code>
       * @return The hardware.
       */
      public java.lang.String getHardware() {
        java.lang.Object ref = hardware_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hardware_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hardware = 2;</code>
       * @return The bytes for hardware.
       */
      public com.google.protobuf.ByteString
          getHardwareBytes() {
        java.lang.Object ref = hardware_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hardware_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hardware = 2;</code>
       * @param value The hardware to set.
       * @return This builder for chaining.
       */
      public Builder setHardware(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        hardware_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hardware = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHardware() {

        hardware_ = getDefaultInstance().getHardware();
        onChanged();
        return this;
      }
      /**
       * <code>string hardware = 2;</code>
       * @param value The bytes for hardware to set.
       * @return This builder for chaining.
       */
      public Builder setHardwareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        hardware_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object software_ = "";
      /**
       * <code>string software = 3;</code>
       * @return The software.
       */
      public java.lang.String getSoftware() {
        java.lang.Object ref = software_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          software_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string software = 3;</code>
       * @return The bytes for software.
       */
      public com.google.protobuf.ByteString
          getSoftwareBytes() {
        java.lang.Object ref = software_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          software_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string software = 3;</code>
       * @param value The software to set.
       * @return This builder for chaining.
       */
      public Builder setSoftware(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        software_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string software = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoftware() {

        software_ = getDefaultInstance().getSoftware();
        onChanged();
        return this;
      }
      /**
       * <code>string software = 3;</code>
       * @param value The bytes for software to set.
       * @return This builder for chaining.
       */
      public Builder setSoftwareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        software_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MobilePhone)
    }

    // @@protoc_insertion_point(class_scope:MobilePhone)
    private static final com.whale.generator.netty.proto.Mobile.MobilePhone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.whale.generator.netty.proto.Mobile.MobilePhone();
    }

    public static com.whale.generator.netty.proto.Mobile.MobilePhone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MobilePhone>
        PARSER = new com.google.protobuf.AbstractParser<MobilePhone>() {
      @java.lang.Override
      public MobilePhone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MobilePhone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MobilePhone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MobilePhone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.whale.generator.netty.proto.Mobile.MobilePhone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MobilePhone_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MobilePhone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mobile.proto\"@\n\013MobilePhone\022\r\n\005brand\030\001" +
      " \001(\t\022\020\n\010hardware\030\002 \001(\t\022\020\n\010software\030\003 \001(\t" +
      "B!\n\037com.whale.generator.netty.protob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MobilePhone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MobilePhone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MobilePhone_descriptor,
        new java.lang.String[] { "Brand", "Hardware", "Software", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
