// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.whale.generator.netty.protocol.protobuf;

public final class MsgBase {
  private MsgBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>string msgId = 1;</code>
     * @return The msgId.
     */
    java.lang.String getMsgId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>string msgId = 1;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.Msg.MessageType msgType = 3;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.Msg.MessageType msgType = 3;</code>
     * @return The msgType.
     */
    com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType getMsgType();

    /**
     * <pre>
     *消息状态
     * </pre>
     *
     * <code>.Msg.MessageStatus msgStatus = 4;</code>
     * @return The enum numeric value on the wire for msgStatus.
     */
    int getMsgStatusValue();
    /**
     * <pre>
     *消息状态
     * </pre>
     *
     * <code>.Msg.MessageStatus msgStatus = 4;</code>
     * @return The msgStatus.
     */
    com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus getMsgStatus();

    /**
     * <pre>
     *接受人id
     * </pre>
     *
     * <code>string accepterId = 5;</code>
     * @return The accepterId.
     */
    java.lang.String getAccepterId();
    /**
     * <pre>
     *接受人id
     * </pre>
     *
     * <code>string accepterId = 5;</code>
     * @return The bytes for accepterId.
     */
    com.google.protobuf.ByteString
        getAccepterIdBytes();

    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>string clusterId = 6;</code>
     * @return The clusterId.
     */
    java.lang.String getClusterId();
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>string clusterId = 6;</code>
     * @return The bytes for clusterId.
     */
    com.google.protobuf.ByteString
        getClusterIdBytes();

    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>.Msg.SendType sendType = 7;</code>
     * @return The enum numeric value on the wire for sendType.
     */
    int getSendTypeValue();
    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>.Msg.SendType sendType = 7;</code>
     * @return The sendType.
     */
    com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType getSendType();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>sint64 sendTime = 8;</code>
     * @return The sendTime.
     */
    long getSendTime();

    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>string sendUserId = 9;</code>
     * @return The sendUserId.
     */
    java.lang.String getSendUserId();
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>string sendUserId = 9;</code>
     * @return The bytes for sendUserId.
     */
    com.google.protobuf.ByteString
        getSendUserIdBytes();
  }
  /**
   * Protobuf type {@code Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      msgId_ = "";
      content_ = "";
      msgType_ = 0;
      msgStatus_ = 0;
      accepterId_ = "";
      clusterId_ = "";
      sendType_ = 0;
      sendUserId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              msgStatus_ = rawValue;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              accepterId_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              clusterId_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              sendType_ = rawValue;
              break;
            }
            case 64: {

              sendTime_ = input.readSInt64();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              sendUserId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whale.generator.netty.protocol.protobuf.MsgBase.internal_static_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whale.generator.netty.protocol.protobuf.MsgBase.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.class, com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.Builder.class);
    }

    /**
     * Protobuf enum {@code Msg.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *常规业务消息
       * </pre>
       *
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0),
      /**
       * <pre>
       *客户端心跳消息
       * </pre>
       *
       * <code>HEARTBEAT_REQUEST = 1;</code>
       */
      HEARTBEAT_REQUEST(1),
      /**
       * <pre>
       *服务端心跳消息
       * </pre>
       *
       * <code>HEARTBEAT_RESPONSE = 2;</code>
       */
      HEARTBEAT_RESPONSE(2),
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>MESSAGE_CHANGE = 3;</code>
       */
      MESSAGE_CHANGE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *常规业务消息
       * </pre>
       *
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <pre>
       *客户端心跳消息
       * </pre>
       *
       * <code>HEARTBEAT_REQUEST = 1;</code>
       */
      public static final int HEARTBEAT_REQUEST_VALUE = 1;
      /**
       * <pre>
       *服务端心跳消息
       * </pre>
       *
       * <code>HEARTBEAT_RESPONSE = 2;</code>
       */
      public static final int HEARTBEAT_RESPONSE_VALUE = 2;
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>MESSAGE_CHANGE = 3;</code>
       */
      public static final int MESSAGE_CHANGE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return HEARTBEAT_REQUEST;
          case 2: return HEARTBEAT_RESPONSE;
          case 3: return MESSAGE_CHANGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Msg.MessageType)
    }

    /**
     * Protobuf enum {@code Msg.MessageStatus}
     */
    public enum MessageStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ALREADY = 0;</code>
       */
      ALREADY(0),
      /**
       * <code>READ = 1;</code>
       */
      READ(1),
      /**
       * <code>RECALL = 2;</code>
       */
      RECALL(2),
      /**
       * <code>REMOVE = 3;</code>
       */
      REMOVE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ALREADY = 0;</code>
       */
      public static final int ALREADY_VALUE = 0;
      /**
       * <code>READ = 1;</code>
       */
      public static final int READ_VALUE = 1;
      /**
       * <code>RECALL = 2;</code>
       */
      public static final int RECALL_VALUE = 2;
      /**
       * <code>REMOVE = 3;</code>
       */
      public static final int REMOVE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageStatus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageStatus forNumber(int value) {
        switch (value) {
          case 0: return ALREADY;
          case 1: return READ;
          case 2: return RECALL;
          case 3: return REMOVE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageStatus>() {
              public MessageStatus findValueByNumber(int number) {
                return MessageStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.getDescriptor().getEnumTypes().get(1);
      }

      private static final MessageStatus[] VALUES = values();

      public static MessageStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Msg.MessageStatus)
    }

    /**
     * Protobuf enum {@code Msg.SendType}
     */
    public enum SendType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *私聊
       * </pre>
       *
       * <code>ACCEPTER = 0;</code>
       */
      ACCEPTER(0),
      /**
       * <pre>
       *群消息
       * </pre>
       *
       * <code>CLUSTER = 1;</code>
       */
      CLUSTER(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *私聊
       * </pre>
       *
       * <code>ACCEPTER = 0;</code>
       */
      public static final int ACCEPTER_VALUE = 0;
      /**
       * <pre>
       *群消息
       * </pre>
       *
       * <code>CLUSTER = 1;</code>
       */
      public static final int CLUSTER_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SendType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static SendType forNumber(int value) {
        switch (value) {
          case 0: return ACCEPTER;
          case 1: return CLUSTER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SendType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SendType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SendType>() {
              public SendType findValueByNumber(int number) {
                return SendType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.getDescriptor().getEnumTypes().get(2);
      }

      private static final SendType[] VALUES = values();

      public static SendType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SendType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Msg.SendType)
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>string msgId = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>string msgId = 1;</code>
     * @return The bytes for msgId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.Msg.MessageType msgType = 3;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.Msg.MessageType msgType = 3;</code>
     * @return The msgType.
     */
    @java.lang.Override public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType getMsgType() {
      @SuppressWarnings("deprecation")
      com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType result = com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType.valueOf(msgType_);
      return result == null ? com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType.UNRECOGNIZED : result;
    }

    public static final int MSGSTATUS_FIELD_NUMBER = 4;
    private int msgStatus_;
    /**
     * <pre>
     *消息状态
     * </pre>
     *
     * <code>.Msg.MessageStatus msgStatus = 4;</code>
     * @return The enum numeric value on the wire for msgStatus.
     */
    @java.lang.Override public int getMsgStatusValue() {
      return msgStatus_;
    }
    /**
     * <pre>
     *消息状态
     * </pre>
     *
     * <code>.Msg.MessageStatus msgStatus = 4;</code>
     * @return The msgStatus.
     */
    @java.lang.Override public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus getMsgStatus() {
      @SuppressWarnings("deprecation")
      com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus result = com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus.valueOf(msgStatus_);
      return result == null ? com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus.UNRECOGNIZED : result;
    }

    public static final int ACCEPTERID_FIELD_NUMBER = 5;
    private volatile java.lang.Object accepterId_;
    /**
     * <pre>
     *接受人id
     * </pre>
     *
     * <code>string accepterId = 5;</code>
     * @return The accepterId.
     */
    @java.lang.Override
    public java.lang.String getAccepterId() {
      java.lang.Object ref = accepterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accepterId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接受人id
     * </pre>
     *
     * <code>string accepterId = 5;</code>
     * @return The bytes for accepterId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccepterIdBytes() {
      java.lang.Object ref = accepterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accepterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLUSTERID_FIELD_NUMBER = 6;
    private volatile java.lang.Object clusterId_;
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>string clusterId = 6;</code>
     * @return The clusterId.
     */
    @java.lang.Override
    public java.lang.String getClusterId() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>string clusterId = 6;</code>
     * @return The bytes for clusterId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClusterIdBytes() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTYPE_FIELD_NUMBER = 7;
    private int sendType_;
    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>.Msg.SendType sendType = 7;</code>
     * @return The enum numeric value on the wire for sendType.
     */
    @java.lang.Override public int getSendTypeValue() {
      return sendType_;
    }
    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>.Msg.SendType sendType = 7;</code>
     * @return The sendType.
     */
    @java.lang.Override public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType getSendType() {
      @SuppressWarnings("deprecation")
      com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType result = com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType.valueOf(sendType_);
      return result == null ? com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType.UNRECOGNIZED : result;
    }

    public static final int SENDTIME_FIELD_NUMBER = 8;
    private long sendTime_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>sint64 sendTime = 8;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return sendTime_;
    }

    public static final int SENDUSERID_FIELD_NUMBER = 9;
    private volatile java.lang.Object sendUserId_;
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>string sendUserId = 9;</code>
     * @return The sendUserId.
     */
    @java.lang.Override
    public java.lang.String getSendUserId() {
      java.lang.Object ref = sendUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sendUserId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>string sendUserId = 9;</code>
     * @return The bytes for sendUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSendUserIdBytes() {
      java.lang.Object ref = sendUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (msgType_ != com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType.NORMAL.getNumber()) {
        output.writeEnum(3, msgType_);
      }
      if (msgStatus_ != com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus.ALREADY.getNumber()) {
        output.writeEnum(4, msgStatus_);
      }
      if (!getAccepterIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, accepterId_);
      }
      if (!getClusterIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, clusterId_);
      }
      if (sendType_ != com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType.ACCEPTER.getNumber()) {
        output.writeEnum(7, sendType_);
      }
      if (sendTime_ != 0L) {
        output.writeSInt64(8, sendTime_);
      }
      if (!getSendUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sendUserId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (msgType_ != com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType.NORMAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, msgType_);
      }
      if (msgStatus_ != com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus.ALREADY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, msgStatus_);
      }
      if (!getAccepterIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, accepterId_);
      }
      if (!getClusterIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, clusterId_);
      }
      if (sendType_ != com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType.ACCEPTER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, sendType_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(8, sendTime_);
      }
      if (!getSendUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, sendUserId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.whale.generator.netty.protocol.protobuf.MsgBase.Msg)) {
        return super.equals(obj);
      }
      com.whale.generator.netty.protocol.protobuf.MsgBase.Msg other = (com.whale.generator.netty.protocol.protobuf.MsgBase.Msg) obj;

      if (!getMsgId()
          .equals(other.getMsgId())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (msgType_ != other.msgType_) return false;
      if (msgStatus_ != other.msgStatus_) return false;
      if (!getAccepterId()
          .equals(other.getAccepterId())) return false;
      if (!getClusterId()
          .equals(other.getClusterId())) return false;
      if (sendType_ != other.sendType_) return false;
      if (getSendTime()
          != other.getSendTime()) return false;
      if (!getSendUserId()
          .equals(other.getSendUserId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + MSGSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + msgStatus_;
      hash = (37 * hash) + ACCEPTERID_FIELD_NUMBER;
      hash = (53 * hash) + getAccepterId().hashCode();
      hash = (37 * hash) + CLUSTERID_FIELD_NUMBER;
      hash = (53 * hash) + getClusterId().hashCode();
      hash = (37 * hash) + SENDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + sendType_;
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      hash = (37 * hash) + SENDUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getSendUserId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.whale.generator.netty.protocol.protobuf.MsgBase.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg)
        com.whale.generator.netty.protocol.protobuf.MsgBase.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whale.generator.netty.protocol.protobuf.MsgBase.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whale.generator.netty.protocol.protobuf.MsgBase.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.class, com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.Builder.class);
      }

      // Construct using com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgId_ = "";

        content_ = "";

        msgType_ = 0;

        msgStatus_ = 0;

        accepterId_ = "";

        clusterId_ = "";

        sendType_ = 0;

        sendTime_ = 0L;

        sendUserId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whale.generator.netty.protocol.protobuf.MsgBase.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg getDefaultInstanceForType() {
        return com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg build() {
        com.whale.generator.netty.protocol.protobuf.MsgBase.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg buildPartial() {
        com.whale.generator.netty.protocol.protobuf.MsgBase.Msg result = new com.whale.generator.netty.protocol.protobuf.MsgBase.Msg(this);
        result.msgId_ = msgId_;
        result.content_ = content_;
        result.msgType_ = msgType_;
        result.msgStatus_ = msgStatus_;
        result.accepterId_ = accepterId_;
        result.clusterId_ = clusterId_;
        result.sendType_ = sendType_;
        result.sendTime_ = sendTime_;
        result.sendUserId_ = sendUserId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whale.generator.netty.protocol.protobuf.MsgBase.Msg) {
          return mergeFrom((com.whale.generator.netty.protocol.protobuf.MsgBase.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whale.generator.netty.protocol.protobuf.MsgBase.Msg other) {
        if (other == com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.getDefaultInstance()) return this;
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.msgStatus_ != 0) {
          setMsgStatusValue(other.getMsgStatusValue());
        }
        if (!other.getAccepterId().isEmpty()) {
          accepterId_ = other.accepterId_;
          onChanged();
        }
        if (!other.getClusterId().isEmpty()) {
          clusterId_ = other.clusterId_;
          onChanged();
        }
        if (other.sendType_ != 0) {
          setSendTypeValue(other.getSendTypeValue());
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        if (!other.getSendUserId().isEmpty()) {
          sendUserId_ = other.sendUserId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whale.generator.netty.protocol.protobuf.MsgBase.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whale.generator.netty.protocol.protobuf.MsgBase.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msgId_ = "";
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>string msgId = 1;</code>
       * @return The msgId.
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>string msgId = 1;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>string msgId = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>string msgId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>string msgId = 1;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 2;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.Msg.MessageType msgType = 3;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @java.lang.Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.Msg.MessageType msgType = 3;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.Msg.MessageType msgType = 3;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType getMsgType() {
        @SuppressWarnings("deprecation")
        com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType result = com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType.valueOf(msgType_);
        return result == null ? com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.Msg.MessageType msgType = 3;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.Msg.MessageType msgType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int msgStatus_ = 0;
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.Msg.MessageStatus msgStatus = 4;</code>
       * @return The enum numeric value on the wire for msgStatus.
       */
      @java.lang.Override public int getMsgStatusValue() {
        return msgStatus_;
      }
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.Msg.MessageStatus msgStatus = 4;</code>
       * @param value The enum numeric value on the wire for msgStatus to set.
       * @return This builder for chaining.
       */
      public Builder setMsgStatusValue(int value) {
        
        msgStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.Msg.MessageStatus msgStatus = 4;</code>
       * @return The msgStatus.
       */
      @java.lang.Override
      public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus getMsgStatus() {
        @SuppressWarnings("deprecation")
        com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus result = com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus.valueOf(msgStatus_);
        return result == null ? com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.Msg.MessageStatus msgStatus = 4;</code>
       * @param value The msgStatus to set.
       * @return This builder for chaining.
       */
      public Builder setMsgStatus(com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.MessageStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.Msg.MessageStatus msgStatus = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgStatus() {
        
        msgStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object accepterId_ = "";
      /**
       * <pre>
       *接受人id
       * </pre>
       *
       * <code>string accepterId = 5;</code>
       * @return The accepterId.
       */
      public java.lang.String getAccepterId() {
        java.lang.Object ref = accepterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accepterId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接受人id
       * </pre>
       *
       * <code>string accepterId = 5;</code>
       * @return The bytes for accepterId.
       */
      public com.google.protobuf.ByteString
          getAccepterIdBytes() {
        java.lang.Object ref = accepterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accepterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接受人id
       * </pre>
       *
       * <code>string accepterId = 5;</code>
       * @param value The accepterId to set.
       * @return This builder for chaining.
       */
      public Builder setAccepterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accepterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接受人id
       * </pre>
       *
       * <code>string accepterId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccepterId() {
        
        accepterId_ = getDefaultInstance().getAccepterId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接受人id
       * </pre>
       *
       * <code>string accepterId = 5;</code>
       * @param value The bytes for accepterId to set.
       * @return This builder for chaining.
       */
      public Builder setAccepterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accepterId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clusterId_ = "";
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>string clusterId = 6;</code>
       * @return The clusterId.
       */
      public java.lang.String getClusterId() {
        java.lang.Object ref = clusterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clusterId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>string clusterId = 6;</code>
       * @return The bytes for clusterId.
       */
      public com.google.protobuf.ByteString
          getClusterIdBytes() {
        java.lang.Object ref = clusterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clusterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>string clusterId = 6;</code>
       * @param value The clusterId to set.
       * @return This builder for chaining.
       */
      public Builder setClusterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clusterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>string clusterId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearClusterId() {
        
        clusterId_ = getDefaultInstance().getClusterId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>string clusterId = 6;</code>
       * @param value The bytes for clusterId to set.
       * @return This builder for chaining.
       */
      public Builder setClusterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clusterId_ = value;
        onChanged();
        return this;
      }

      private int sendType_ = 0;
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>.Msg.SendType sendType = 7;</code>
       * @return The enum numeric value on the wire for sendType.
       */
      @java.lang.Override public int getSendTypeValue() {
        return sendType_;
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>.Msg.SendType sendType = 7;</code>
       * @param value The enum numeric value on the wire for sendType to set.
       * @return This builder for chaining.
       */
      public Builder setSendTypeValue(int value) {
        
        sendType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>.Msg.SendType sendType = 7;</code>
       * @return The sendType.
       */
      @java.lang.Override
      public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType getSendType() {
        @SuppressWarnings("deprecation")
        com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType result = com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType.valueOf(sendType_);
        return result == null ? com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>.Msg.SendType sendType = 7;</code>
       * @param value The sendType to set.
       * @return This builder for chaining.
       */
      public Builder setSendType(com.whale.generator.netty.protocol.protobuf.MsgBase.Msg.SendType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sendType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>.Msg.SendType sendType = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendType() {
        
        sendType_ = 0;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>sint64 sendTime = 8;</code>
       * @return The sendTime.
       */
      @java.lang.Override
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>sint64 sendTime = 8;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(long value) {
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>sint64 sendTime = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object sendUserId_ = "";
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>string sendUserId = 9;</code>
       * @return The sendUserId.
       */
      public java.lang.String getSendUserId() {
        java.lang.Object ref = sendUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sendUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>string sendUserId = 9;</code>
       * @return The bytes for sendUserId.
       */
      public com.google.protobuf.ByteString
          getSendUserIdBytes() {
        java.lang.Object ref = sendUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>string sendUserId = 9;</code>
       * @param value The sendUserId to set.
       * @return This builder for chaining.
       */
      public Builder setSendUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>string sendUserId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendUserId() {
        
        sendUserId_ = getDefaultInstance().getSendUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>string sendUserId = 9;</code>
       * @param value The bytes for sendUserId to set.
       * @return This builder for chaining.
       */
      public Builder setSendUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sendUserId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg)
    }

    // @@protoc_insertion_point(class_scope:Msg)
    private static final com.whale.generator.netty.protocol.protobuf.MsgBase.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.whale.generator.netty.protocol.protobuf.MsgBase.Msg();
    }

    public static com.whale.generator.netty.protocol.protobuf.MsgBase.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.whale.generator.netty.protocol.protobuf.MsgBase.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\032\037google/protobuf/timesta" +
      "mp.proto\"\242\003\n\003Msg\022\r\n\005msgId\030\001 \001(\t\022\017\n\007conte" +
      "nt\030\002 \001(\t\022!\n\007msgType\030\003 \001(\0162\020.Msg.MessageT" +
      "ype\022%\n\tmsgStatus\030\004 \001(\0162\022.Msg.MessageStat" +
      "us\022\022\n\naccepterId\030\005 \001(\t\022\021\n\tclusterId\030\006 \001(" +
      "\t\022\037\n\010sendType\030\007 \001(\0162\r.Msg.SendType\022\020\n\010se" +
      "ndTime\030\010 \001(\022\022\022\n\nsendUserId\030\t \001(\t\"\\\n\013Mess" +
      "ageType\022\n\n\006NORMAL\020\000\022\025\n\021HEARTBEAT_REQUEST" +
      "\020\001\022\026\n\022HEARTBEAT_RESPONSE\020\002\022\022\n\016MESSAGE_CH" +
      "ANGE\020\003\">\n\rMessageStatus\022\013\n\007ALREADY\020\000\022\010\n\004" +
      "READ\020\001\022\n\n\006RECALL\020\002\022\n\n\006REMOVE\020\003\"%\n\010SendTy" +
      "pe\022\014\n\010ACCEPTER\020\000\022\013\n\007CLUSTER\020\001B6\n+com.wha" +
      "le.generator.netty.protocol.protobufB\007Ms" +
      "gBaseP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_descriptor,
        new java.lang.String[] { "MsgId", "Content", "MsgType", "MsgStatus", "AccepterId", "ClusterId", "SendType", "SendTime", "SendUserId", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
