// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.whale.generator.netty.common.protocol;

public final class Cmd {
  private Cmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   * 指令类型
   * </pre>
   *
   * Protobuf enum {@code Command}
   */
  public enum Command
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *常规业务消息
     * </pre>
     *
     * <code>NORMAL = 0;</code>
     */
    NORMAL(0),
    /**
     * <pre>
     *客户端心跳消息
     * </pre>
     *
     * <code>HEARTBEAT_REQUEST = 1;</code>
     */
    HEARTBEAT_REQUEST(1),
    /**
     * <pre>
     * 服务端心跳消息
     * </pre>
     *
     * <code>HEARTBEAT_RESPONSE = 2;</code>
     */
    HEARTBEAT_RESPONSE(2),
    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>MESSAGE_CHANGE = 3;</code>
     */
    MESSAGE_CHANGE(3),
    /**
     * <pre>
     *认证
     * </pre>
     *
     * <code>AUTH = 4;</code>
     */
    AUTH(4),
    /**
     * <pre>
     *系统消息
     * </pre>
     *
     * <code>SYSTEM = 5;</code>
     */
    SYSTEM(5),
    /**
     * <pre>
     *发起好友申请 （发起方）
     * </pre>
     *
     * <code>BULL_SPONSOR = 6;</code>
     */
    BULL_SPONSOR(6),
    /**
     * <pre>
     *好友申请消息（询问方）
     * </pre>
     *
     * <code>BULL_ASK = 7;</code>
     */
    BULL_ASK(7),
    /**
     * <pre>
     * 好友申请结果
     * </pre>
     *
     * <code>BULL_RESULT = 8;</code>
     */
    BULL_RESULT(8),
    /**
     * <pre>
     *获取好有列表
     * </pre>
     *
     * <code>BULL_LIST = 9;</code>
     */
    BULL_LIST(9),
    /**
     * <pre>
     *好友删除
     * </pre>
     *
     * <code>BULL_DELETE = 10;</code>
     */
    BULL_DELETE(10),
    /**
     * <pre>
     **
     * 通知类消息，
     * 如：好友拒接申请和一些通知类型的消息
     * </pre>
     *
     * <code>INFORM = 11;</code>
     */
    INFORM(11),
    /**
     * <pre>
     **
     * 发送消息时，如果对方不在线，消息存储后，等待上线后将离线消息推送给用户
     * </pre>
     *
     * <code>OFFLINE_MSG = 12;</code>
     */
    OFFLINE_MSG(12),
    /**
     * <pre>
     **
     * 通讯只用了userId，想获取这个用户信息可以使用该类型消息，来获取详细信息
     * </pre>
     *
     * <code>QUERY = 13;</code>
     */
    QUERY(13),
    ;

    /**
     * <pre>
     *常规业务消息
     * </pre>
     *
     * <code>NORMAL = 0;</code>
     */
    public static final int NORMAL_VALUE = 0;
    /**
     * <pre>
     *客户端心跳消息
     * </pre>
     *
     * <code>HEARTBEAT_REQUEST = 1;</code>
     */
    public static final int HEARTBEAT_REQUEST_VALUE = 1;
    /**
     * <pre>
     * 服务端心跳消息
     * </pre>
     *
     * <code>HEARTBEAT_RESPONSE = 2;</code>
     */
    public static final int HEARTBEAT_RESPONSE_VALUE = 2;
    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>MESSAGE_CHANGE = 3;</code>
     */
    public static final int MESSAGE_CHANGE_VALUE = 3;
    /**
     * <pre>
     *认证
     * </pre>
     *
     * <code>AUTH = 4;</code>
     */
    public static final int AUTH_VALUE = 4;
    /**
     * <pre>
     *系统消息
     * </pre>
     *
     * <code>SYSTEM = 5;</code>
     */
    public static final int SYSTEM_VALUE = 5;
    /**
     * <pre>
     *发起好友申请 （发起方）
     * </pre>
     *
     * <code>BULL_SPONSOR = 6;</code>
     */
    public static final int BULL_SPONSOR_VALUE = 6;
    /**
     * <pre>
     *好友申请消息（询问方）
     * </pre>
     *
     * <code>BULL_ASK = 7;</code>
     */
    public static final int BULL_ASK_VALUE = 7;
    /**
     * <pre>
     * 好友申请结果
     * </pre>
     *
     * <code>BULL_RESULT = 8;</code>
     */
    public static final int BULL_RESULT_VALUE = 8;
    /**
     * <pre>
     *获取好有列表
     * </pre>
     *
     * <code>BULL_LIST = 9;</code>
     */
    public static final int BULL_LIST_VALUE = 9;
    /**
     * <pre>
     *好友删除
     * </pre>
     *
     * <code>BULL_DELETE = 10;</code>
     */
    public static final int BULL_DELETE_VALUE = 10;
    /**
     * <pre>
     **
     * 通知类消息，
     * 如：好友拒接申请和一些通知类型的消息
     * </pre>
     *
     * <code>INFORM = 11;</code>
     */
    public static final int INFORM_VALUE = 11;
    /**
     * <pre>
     **
     * 发送消息时，如果对方不在线，消息存储后，等待上线后将离线消息推送给用户
     * </pre>
     *
     * <code>OFFLINE_MSG = 12;</code>
     */
    public static final int OFFLINE_MSG_VALUE = 12;
    /**
     * <pre>
     **
     * 通讯只用了userId，想获取这个用户信息可以使用该类型消息，来获取详细信息
     * </pre>
     *
     * <code>QUERY = 13;</code>
     */
    public static final int QUERY_VALUE = 13;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Command valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Command forNumber(int value) {
      switch (value) {
        case 0: return NORMAL;
        case 1: return HEARTBEAT_REQUEST;
        case 2: return HEARTBEAT_RESPONSE;
        case 3: return MESSAGE_CHANGE;
        case 4: return AUTH;
        case 5: return SYSTEM;
        case 6: return BULL_SPONSOR;
        case 7: return BULL_ASK;
        case 8: return BULL_RESULT;
        case 9: return BULL_LIST;
        case 10: return BULL_DELETE;
        case 11: return INFORM;
        case 12: return OFFLINE_MSG;
        case 13: return QUERY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Command>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Command> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Command>() {
            public Command findValueByNumber(int number) {
              return Command.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.whale.generator.netty.common.protocol.Cmd.getDescriptor().getEnumTypes().get(0);
    }

    private static final Command[] VALUES = values();

    public static Command valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Command(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Command)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto*\347\001\n\007Command\022\n\n\006NORMAL\020\000\022" +
      "\025\n\021HEARTBEAT_REQUEST\020\001\022\026\n\022HEARTBEAT_RESP" +
      "ONSE\020\002\022\022\n\016MESSAGE_CHANGE\020\003\022\010\n\004AUTH\020\004\022\n\n\006" +
      "SYSTEM\020\005\022\020\n\014BULL_SPONSOR\020\006\022\014\n\010BULL_ASK\020\007" +
      "\022\017\n\013BULL_RESULT\020\010\022\r\n\tBULL_LIST\020\t\022\017\n\013BULL" +
      "_DELETE\020\n\022\n\n\006INFORM\020\013\022\017\n\013OFFLINE_MSG\020\014\022\t" +
      "\n\005QUERY\020\rB0\n)com.whale.generator.netty.c" +
      "ommon.protocolB\003Cmd"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
