// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.whale.generator.netty.common.protocol;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   * 指令类型
   * </pre>
   *
   * Protobuf enum {@code CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     **
     * 常规业务消息
     * </pre>
     *
     * <code>NORMAL = 0;</code>
     */
    NORMAL(0),
    /**
     * <pre>
     **
     * 客户端心跳消息
     * </pre>
     *
     * <code>HEARTBEAT_REQUEST = 1;</code>
     */
    HEARTBEAT_REQUEST(1),
    /**
     * <pre>
     **
     * 服务端心跳消息
     * </pre>
     *
     * <code>HEARTBEAT_RESPONSE = 2;</code>
     */
    HEARTBEAT_RESPONSE(2),
    /**
     * <pre>
     **
     * 消息状态改变
     * </pre>
     *
     * <code>MESSAGE_CHANGE = 3;</code>
     */
    MESSAGE_CHANGE(3),
    /**
     * <pre>
     **
     * 认证
     * </pre>
     *
     * <code>AUTH = 4;</code>
     */
    AUTH(4),
    /**
     * <pre>
     **
     * 系统消息
     * </pre>
     *
     * <code>SYSTEM = 5;</code>
     */
    SYSTEM(5),
    ;

    /**
     * <pre>
     **
     * 常规业务消息
     * </pre>
     *
     * <code>NORMAL = 0;</code>
     */
    public static final int NORMAL_VALUE = 0;
    /**
     * <pre>
     **
     * 客户端心跳消息
     * </pre>
     *
     * <code>HEARTBEAT_REQUEST = 1;</code>
     */
    public static final int HEARTBEAT_REQUEST_VALUE = 1;
    /**
     * <pre>
     **
     * 服务端心跳消息
     * </pre>
     *
     * <code>HEARTBEAT_RESPONSE = 2;</code>
     */
    public static final int HEARTBEAT_RESPONSE_VALUE = 2;
    /**
     * <pre>
     **
     * 消息状态改变
     * </pre>
     *
     * <code>MESSAGE_CHANGE = 3;</code>
     */
    public static final int MESSAGE_CHANGE_VALUE = 3;
    /**
     * <pre>
     **
     * 认证
     * </pre>
     *
     * <code>AUTH = 4;</code>
     */
    public static final int AUTH_VALUE = 4;
    /**
     * <pre>
     **
     * 系统消息
     * </pre>
     *
     * <code>SYSTEM = 5;</code>
     */
    public static final int SYSTEM_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return NORMAL;
        case 1: return HEARTBEAT_REQUEST;
        case 2: return HEARTBEAT_RESPONSE;
        case 3: return MESSAGE_CHANGE;
        case 4: return AUTH;
        case 5: return SYSTEM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.whale.generator.netty.common.protocol.Command.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CommandType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto*r\n\013CommandType\022\n\n\006NORMAL" +
      "\020\000\022\025\n\021HEARTBEAT_REQUEST\020\001\022\026\n\022HEARTBEAT_R" +
      "ESPONSE\020\002\022\022\n\016MESSAGE_CHANGE\020\003\022\010\n\004AUTH\020\004\022" +
      "\n\n\006SYSTEM\020\005B4\n)com.whale.generator.netty" +
      ".common.protocolB\007Command"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
