// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.whale.generator.netty.common.protocol;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   * 指令类型
   * </pre>
   *
   * Protobuf enum {@code SendType}
   */
  public enum SendType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *私聊
     * </pre>
     *
     * <code>ACCEPTER = 0;</code>
     */
    ACCEPTER(0),
    /**
     * <pre>
     *群消息
     * </pre>
     *
     * <code>CLUSTER = 1;</code>
     */
    CLUSTER(1),
    ;

    /**
     * <pre>
     *私聊
     * </pre>
     *
     * <code>ACCEPTER = 0;</code>
     */
    public static final int ACCEPTER_VALUE = 0;
    /**
     * <pre>
     *群消息
     * </pre>
     *
     * <code>CLUSTER = 1;</code>
     */
    public static final int CLUSTER_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SendType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SendType forNumber(int value) {
      switch (value) {
        case 0: return ACCEPTER;
        case 1: return CLUSTER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SendType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SendType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SendType>() {
            public SendType findValueByNumber(int number) {
              return SendType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.whale.generator.netty.common.protocol.Msg.getDescriptor().getEnumTypes().get(0);
    }

    private static final SendType[] VALUES = values();

    public static SendType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SendType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SendType)
  }

  /**
   * <pre>
   **
   * 消息改变类型
   * </pre>
   *
   * Protobuf enum {@code StatusType}
   */
  public enum StatusType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未读
     * </pre>
     *
     * <code>ALREADY = 0;</code>
     */
    ALREADY(0),
    /**
     * <pre>
     *已读
     * </pre>
     *
     * <code>READ = 1;</code>
     */
    READ(1),
    /**
     * <pre>
     *撤回
     * </pre>
     *
     * <code>RECALL = 2;</code>
     */
    RECALL(2),
    /**
     * <pre>
     *删除
     * </pre>
     *
     * <code>REMOVE = 3;</code>
     */
    REMOVE(3),
    ;

    /**
     * <pre>
     *未读
     * </pre>
     *
     * <code>ALREADY = 0;</code>
     */
    public static final int ALREADY_VALUE = 0;
    /**
     * <pre>
     *已读
     * </pre>
     *
     * <code>READ = 1;</code>
     */
    public static final int READ_VALUE = 1;
    /**
     * <pre>
     *撤回
     * </pre>
     *
     * <code>RECALL = 2;</code>
     */
    public static final int RECALL_VALUE = 2;
    /**
     * <pre>
     *删除
     * </pre>
     *
     * <code>REMOVE = 3;</code>
     */
    public static final int REMOVE_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StatusType forNumber(int value) {
      switch (value) {
        case 0: return ALREADY;
        case 1: return READ;
        case 2: return RECALL;
        case 3: return REMOVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusType>() {
            public StatusType findValueByNumber(int number) {
              return StatusType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.whale.generator.netty.common.protocol.Msg.getDescriptor().getEnumTypes().get(1);
    }

    private static final StatusType[] VALUES = values();

    public static StatusType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StatusType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:StatusType)
  }

  public interface BaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Base)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *客户端消息id
     * </pre>
     *
     * <code>optional string cMsgId = 2;</code>
     * @return Whether the cMsgId field is set.
     */
    boolean hasCMsgId();
    /**
     * <pre>
     *客户端消息id
     * </pre>
     *
     * <code>optional string cMsgId = 2;</code>
     * @return The cMsgId.
     */
    java.lang.String getCMsgId();
    /**
     * <pre>
     *客户端消息id
     * </pre>
     *
     * <code>optional string cMsgId = 2;</code>
     * @return The bytes for cMsgId.
     */
    com.google.protobuf.ByteString
        getCMsgIdBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 3;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .Command cmd = 4;</code>
     * @return Whether the cmd field is set.
     */
    boolean hasCmd();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .Command cmd = 4;</code>
     * @return The cmd.
     */
    com.whale.generator.netty.common.protocol.Cmd.Command getCmd();

    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return Whether the accepterId field is set.
     */
    boolean hasAccepterId();
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return The accepterId.
     */
    java.lang.String getAccepterId();
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return The bytes for accepterId.
     */
    com.google.protobuf.ByteString
        getAccepterIdBytes();

    /**
     * <pre>
     *发送的时间戳
     * </pre>
     *
     * <code>required sint64 sendTime = 9;</code>
     * @return Whether the sendTime field is set.
     */
    boolean hasSendTime();
    /**
     * <pre>
     *发送的时间戳
     * </pre>
     *
     * <code>required sint64 sendTime = 9;</code>
     * @return The sendTime.
     */
    long getSendTime();

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return Whether the msgId field is set.
     */
    boolean hasMsgId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return The msgId.
     */
    java.lang.String getMsgId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>optional .StatusType msgStatus = 6;</code>
     * @return Whether the msgStatus field is set.
     */
    boolean hasMsgStatus();
    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>optional .StatusType msgStatus = 6;</code>
     * @return The msgStatus.
     */
    com.whale.generator.netty.common.protocol.Msg.StatusType getMsgStatus();

    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 7;</code>
     * @return Whether the clusterId field is set.
     */
    boolean hasClusterId();
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 7;</code>
     * @return The clusterId.
     */
    java.lang.String getClusterId();
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 7;</code>
     * @return The bytes for clusterId.
     */
    com.google.protobuf.ByteString
        getClusterIdBytes();

    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>optional .SendType sendType = 8;</code>
     * @return Whether the sendType field is set.
     */
    boolean hasSendType();
    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>optional .SendType sendType = 8;</code>
     * @return The sendType.
     */
    com.whale.generator.netty.common.protocol.Msg.SendType getSendType();

    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 10;</code>
     * @return Whether the sendUserId field is set.
     */
    boolean hasSendUserId();
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 10;</code>
     * @return The sendUserId.
     */
    java.lang.String getSendUserId();
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 10;</code>
     * @return The bytes for sendUserId.
     */
    com.google.protobuf.ByteString
        getSendUserIdBytes();

    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 11;</code>
     * @return Whether the token field is set.
     */
    boolean hasToken();
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 11;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 11;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code Base}
   */
  public static final class Base extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Base)
      BaseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Base.newBuilder() to construct.
    private Base(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    public Base() {
      cMsgId_ = "";
      content_ = "";
      cmd_ = 0;
      accepterId_ = "";
      msgId_ = "";
      msgStatus_ = 0;
      clusterId_ = "";
      sendType_ = 0;
      sendUserId_ = "";
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Base();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Base(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              msgId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              cMsgId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              content_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.whale.generator.netty.common.protocol.Cmd.Command value = com.whale.generator.netty.common.protocol.Cmd.Command.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                cmd_ = rawValue;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              accepterId_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.whale.generator.netty.common.protocol.Msg.StatusType value = com.whale.generator.netty.common.protocol.Msg.StatusType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                msgStatus_ = rawValue;
              }
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              clusterId_ = bs;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.whale.generator.netty.common.protocol.Msg.SendType value = com.whale.generator.netty.common.protocol.Msg.SendType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000100;
                sendType_ = rawValue;
              }
              break;
            }
            case 72: {
              bitField0_ |= 0x00000010;
              sendTime_ = input.readSInt64();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              sendUserId_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              token_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whale.generator.netty.common.protocol.Msg.internal_static_Base_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whale.generator.netty.common.protocol.Msg.internal_static_Base_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whale.generator.netty.common.protocol.Msg.Base.class, com.whale.generator.netty.common.protocol.Msg.Base.Builder.class);
    }

    private int bitField0_;
    public static final int CMSGID_FIELD_NUMBER = 2;
    private volatile java.lang.Object cMsgId_;
    /**
     * <pre>
     *客户端消息id
     * </pre>
     *
     * <code>optional string cMsgId = 2;</code>
     * @return Whether the cMsgId field is set.
     */
    @java.lang.Override
    public boolean hasCMsgId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *客户端消息id
     * </pre>
     *
     * <code>optional string cMsgId = 2;</code>
     * @return The cMsgId.
     */
    @java.lang.Override
    public java.lang.String getCMsgId() {
      java.lang.Object ref = cMsgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cMsgId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *客户端消息id
     * </pre>
     *
     * <code>optional string cMsgId = 2;</code>
     * @return The bytes for cMsgId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCMsgIdBytes() {
      java.lang.Object ref = cMsgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 3;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 4;
    private int cmd_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .Command cmd = 4;</code>
     * @return Whether the cmd field is set.
     */
    @java.lang.Override public boolean hasCmd() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .Command cmd = 4;</code>
     * @return The cmd.
     */
    @java.lang.Override public com.whale.generator.netty.common.protocol.Cmd.Command getCmd() {
      @SuppressWarnings("deprecation")
      com.whale.generator.netty.common.protocol.Cmd.Command result = com.whale.generator.netty.common.protocol.Cmd.Command.valueOf(cmd_);
      return result == null ? com.whale.generator.netty.common.protocol.Cmd.Command.NORMAL : result;
    }

    public static final int ACCEPTERID_FIELD_NUMBER = 5;
    private volatile java.lang.Object accepterId_;
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return Whether the accepterId field is set.
     */
    @java.lang.Override
    public boolean hasAccepterId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return The accepterId.
     */
    @java.lang.Override
    public java.lang.String getAccepterId() {
      java.lang.Object ref = accepterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accepterId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return The bytes for accepterId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccepterIdBytes() {
      java.lang.Object ref = accepterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accepterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 9;
    private long sendTime_;
    /**
     * <pre>
     *发送的时间戳
     * </pre>
     *
     * <code>required sint64 sendTime = 9;</code>
     * @return Whether the sendTime field is set.
     */
    @java.lang.Override
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *发送的时间戳
     * </pre>
     *
     * <code>required sint64 sendTime = 9;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return sendTime_;
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return Whether the msgId field is set.
     */
    @java.lang.Override
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return The bytes for msgId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGSTATUS_FIELD_NUMBER = 6;
    private int msgStatus_;
    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>optional .StatusType msgStatus = 6;</code>
     * @return Whether the msgStatus field is set.
     */
    @java.lang.Override public boolean hasMsgStatus() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>optional .StatusType msgStatus = 6;</code>
     * @return The msgStatus.
     */
    @java.lang.Override public com.whale.generator.netty.common.protocol.Msg.StatusType getMsgStatus() {
      @SuppressWarnings("deprecation")
      com.whale.generator.netty.common.protocol.Msg.StatusType result = com.whale.generator.netty.common.protocol.Msg.StatusType.valueOf(msgStatus_);
      return result == null ? com.whale.generator.netty.common.protocol.Msg.StatusType.ALREADY : result;
    }

    public static final int CLUSTERID_FIELD_NUMBER = 7;
    private volatile java.lang.Object clusterId_;
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 7;</code>
     * @return Whether the clusterId field is set.
     */
    @java.lang.Override
    public boolean hasClusterId() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 7;</code>
     * @return The clusterId.
     */
    @java.lang.Override
    public java.lang.String getClusterId() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clusterId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 7;</code>
     * @return The bytes for clusterId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClusterIdBytes() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTYPE_FIELD_NUMBER = 8;
    private int sendType_;
    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>optional .SendType sendType = 8;</code>
     * @return Whether the sendType field is set.
     */
    @java.lang.Override public boolean hasSendType() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>optional .SendType sendType = 8;</code>
     * @return The sendType.
     */
    @java.lang.Override public com.whale.generator.netty.common.protocol.Msg.SendType getSendType() {
      @SuppressWarnings("deprecation")
      com.whale.generator.netty.common.protocol.Msg.SendType result = com.whale.generator.netty.common.protocol.Msg.SendType.valueOf(sendType_);
      return result == null ? com.whale.generator.netty.common.protocol.Msg.SendType.ACCEPTER : result;
    }

    public static final int SENDUSERID_FIELD_NUMBER = 10;
    private volatile java.lang.Object sendUserId_;
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 10;</code>
     * @return Whether the sendUserId field is set.
     */
    @java.lang.Override
    public boolean hasSendUserId() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 10;</code>
     * @return The sendUserId.
     */
    @java.lang.Override
    public java.lang.String getSendUserId() {
      java.lang.Object ref = sendUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sendUserId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 10;</code>
     * @return The bytes for sendUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSendUserIdBytes() {
      java.lang.Object ref = sendUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 11;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 11;</code>
     * @return Whether the token field is set.
     */
    @java.lang.Override
    public boolean hasToken() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 11;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 11;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSendTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cMsgId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(4, cmd_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, accepterId_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeEnum(6, msgStatus_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, clusterId_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeEnum(8, sendType_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeSInt64(9, sendTime_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, sendUserId_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cMsgId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, cmd_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, accepterId_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, msgStatus_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, clusterId_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, sendType_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(9, sendTime_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, sendUserId_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.whale.generator.netty.common.protocol.Msg.Base)) {
        return super.equals(obj);
      }
      com.whale.generator.netty.common.protocol.Msg.Base other = (com.whale.generator.netty.common.protocol.Msg.Base) obj;

      if (hasCMsgId() != other.hasCMsgId()) return false;
      if (hasCMsgId()) {
        if (!getCMsgId()
            .equals(other.getCMsgId())) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasCmd() != other.hasCmd()) return false;
      if (hasCmd()) {
        if (cmd_ != other.cmd_) return false;
      }
      if (hasAccepterId() != other.hasAccepterId()) return false;
      if (hasAccepterId()) {
        if (!getAccepterId()
            .equals(other.getAccepterId())) return false;
      }
      if (hasSendTime() != other.hasSendTime()) return false;
      if (hasSendTime()) {
        if (getSendTime()
            != other.getSendTime()) return false;
      }
      if (hasMsgId() != other.hasMsgId()) return false;
      if (hasMsgId()) {
        if (!getMsgId()
            .equals(other.getMsgId())) return false;
      }
      if (hasMsgStatus() != other.hasMsgStatus()) return false;
      if (hasMsgStatus()) {
        if (msgStatus_ != other.msgStatus_) return false;
      }
      if (hasClusterId() != other.hasClusterId()) return false;
      if (hasClusterId()) {
        if (!getClusterId()
            .equals(other.getClusterId())) return false;
      }
      if (hasSendType() != other.hasSendType()) return false;
      if (hasSendType()) {
        if (sendType_ != other.sendType_) return false;
      }
      if (hasSendUserId() != other.hasSendUserId()) return false;
      if (hasSendUserId()) {
        if (!getSendUserId()
            .equals(other.getSendUserId())) return false;
      }
      if (hasToken() != other.hasToken()) return false;
      if (hasToken()) {
        if (!getToken()
            .equals(other.getToken())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCMsgId()) {
        hash = (37 * hash) + CMSGID_FIELD_NUMBER;
        hash = (53 * hash) + getCMsgId().hashCode();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasCmd()) {
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + cmd_;
      }
      if (hasAccepterId()) {
        hash = (37 * hash) + ACCEPTERID_FIELD_NUMBER;
        hash = (53 * hash) + getAccepterId().hashCode();
      }
      if (hasSendTime()) {
        hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSendTime());
      }
      if (hasMsgId()) {
        hash = (37 * hash) + MSGID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId().hashCode();
      }
      if (hasMsgStatus()) {
        hash = (37 * hash) + MSGSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + msgStatus_;
      }
      if (hasClusterId()) {
        hash = (37 * hash) + CLUSTERID_FIELD_NUMBER;
        hash = (53 * hash) + getClusterId().hashCode();
      }
      if (hasSendType()) {
        hash = (37 * hash) + SENDTYPE_FIELD_NUMBER;
        hash = (53 * hash) + sendType_;
      }
      if (hasSendUserId()) {
        hash = (37 * hash) + SENDUSERID_FIELD_NUMBER;
        hash = (53 * hash) + getSendUserId().hashCode();
      }
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.common.protocol.Msg.Base parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.whale.generator.netty.common.protocol.Msg.Base prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Base}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Base)
        com.whale.generator.netty.common.protocol.Msg.BaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whale.generator.netty.common.protocol.Msg.internal_static_Base_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whale.generator.netty.common.protocol.Msg.internal_static_Base_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whale.generator.netty.common.protocol.Msg.Base.class, com.whale.generator.netty.common.protocol.Msg.Base.Builder.class);
      }

      // Construct using com.whale.generator.netty.common.protocol.Msg.Base.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cMsgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        accepterId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sendTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        msgStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        clusterId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        sendType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        sendUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whale.generator.netty.common.protocol.Msg.internal_static_Base_descriptor;
      }

      @java.lang.Override
      public com.whale.generator.netty.common.protocol.Msg.Base getDefaultInstanceForType() {
        return com.whale.generator.netty.common.protocol.Msg.Base.getDefaultInstance();
      }

      @java.lang.Override
      public com.whale.generator.netty.common.protocol.Msg.Base build() {
        com.whale.generator.netty.common.protocol.Msg.Base result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.whale.generator.netty.common.protocol.Msg.Base buildPartial() {
        com.whale.generator.netty.common.protocol.Msg.Base result = new com.whale.generator.netty.common.protocol.Msg.Base(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cMsgId_ = cMsgId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.accepterId_ = accepterId_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sendTime_ = sendTime_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msgStatus_ = msgStatus_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.clusterId_ = clusterId_;
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000100;
        }
        result.sendType_ = sendType_;
        if (((from_bitField0_ & 0x00000200) != 0)) {
          to_bitField0_ |= 0x00000200;
        }
        result.sendUserId_ = sendUserId_;
        if (((from_bitField0_ & 0x00000400) != 0)) {
          to_bitField0_ |= 0x00000400;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whale.generator.netty.common.protocol.Msg.Base) {
          return mergeFrom((com.whale.generator.netty.common.protocol.Msg.Base)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whale.generator.netty.common.protocol.Msg.Base other) {
        if (other == com.whale.generator.netty.common.protocol.Msg.Base.getDefaultInstance()) return this;
        if (other.hasCMsgId()) {
          bitField0_ |= 0x00000001;
          cMsgId_ = other.cMsgId_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasAccepterId()) {
          bitField0_ |= 0x00000008;
          accepterId_ = other.accepterId_;
          onChanged();
        }
        if (other.hasSendTime()) {
          setSendTime(other.getSendTime());
        }
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000020;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasMsgStatus()) {
          setMsgStatus(other.getMsgStatus());
        }
        if (other.hasClusterId()) {
          bitField0_ |= 0x00000080;
          clusterId_ = other.clusterId_;
          onChanged();
        }
        if (other.hasSendType()) {
          setSendType(other.getSendType());
        }
        if (other.hasSendUserId()) {
          bitField0_ |= 0x00000200;
          sendUserId_ = other.sendUserId_;
          onChanged();
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000400;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCmd()) {
          return false;
        }
        if (!hasSendTime()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whale.generator.netty.common.protocol.Msg.Base parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whale.generator.netty.common.protocol.Msg.Base) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object cMsgId_ = "";
      /**
       * <pre>
       *客户端消息id
       * </pre>
       *
       * <code>optional string cMsgId = 2;</code>
       * @return Whether the cMsgId field is set.
       */
      public boolean hasCMsgId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *客户端消息id
       * </pre>
       *
       * <code>optional string cMsgId = 2;</code>
       * @return The cMsgId.
       */
      public java.lang.String getCMsgId() {
        java.lang.Object ref = cMsgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cMsgId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户端消息id
       * </pre>
       *
       * <code>optional string cMsgId = 2;</code>
       * @return The bytes for cMsgId.
       */
      public com.google.protobuf.ByteString
          getCMsgIdBytes() {
        java.lang.Object ref = cMsgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cMsgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户端消息id
       * </pre>
       *
       * <code>optional string cMsgId = 2;</code>
       * @param value The cMsgId to set.
       * @return This builder for chaining.
       */
      public Builder setCMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端消息id
       * </pre>
       *
       * <code>optional string cMsgId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cMsgId_ = getDefaultInstance().getCMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端消息id
       * </pre>
       *
       * <code>optional string cMsgId = 2;</code>
       * @param value The bytes for cMsgId to set.
       * @return This builder for chaining.
       */
      public Builder setCMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cMsgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 3;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      private int cmd_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .Command cmd = 4;</code>
       * @return Whether the cmd field is set.
       */
      @java.lang.Override public boolean hasCmd() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .Command cmd = 4;</code>
       * @return The cmd.
       */
      @java.lang.Override
      public com.whale.generator.netty.common.protocol.Cmd.Command getCmd() {
        @SuppressWarnings("deprecation")
        com.whale.generator.netty.common.protocol.Cmd.Command result = com.whale.generator.netty.common.protocol.Cmd.Command.valueOf(cmd_);
        return result == null ? com.whale.generator.netty.common.protocol.Cmd.Command.NORMAL : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .Command cmd = 4;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(com.whale.generator.netty.common.protocol.Cmd.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .Command cmd = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object accepterId_ = "";
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @return Whether the accepterId field is set.
       */
      public boolean hasAccepterId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @return The accepterId.
       */
      public java.lang.String getAccepterId() {
        java.lang.Object ref = accepterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accepterId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @return The bytes for accepterId.
       */
      public com.google.protobuf.ByteString
          getAccepterIdBytes() {
        java.lang.Object ref = accepterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accepterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @param value The accepterId to set.
       * @return This builder for chaining.
       */
      public Builder setAccepterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        accepterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccepterId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        accepterId_ = getDefaultInstance().getAccepterId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @param value The bytes for accepterId to set.
       * @return This builder for chaining.
       */
      public Builder setAccepterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        accepterId_ = value;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <pre>
       *发送的时间戳
       * </pre>
       *
       * <code>required sint64 sendTime = 9;</code>
       * @return Whether the sendTime field is set.
       */
      @java.lang.Override
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *发送的时间戳
       * </pre>
       *
       * <code>required sint64 sendTime = 9;</code>
       * @return The sendTime.
       */
      @java.lang.Override
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <pre>
       *发送的时间戳
       * </pre>
       *
       * <code>required sint64 sendTime = 9;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(long value) {
        bitField0_ |= 0x00000010;
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的时间戳
       * </pre>
       *
       * <code>required sint64 sendTime = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msgId_ = "";
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @return Whether the msgId field is set.
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @return The msgId.
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgId_ = value;
        onChanged();
        return this;
      }

      private int msgStatus_ = 0;
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>optional .StatusType msgStatus = 6;</code>
       * @return Whether the msgStatus field is set.
       */
      @java.lang.Override public boolean hasMsgStatus() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>optional .StatusType msgStatus = 6;</code>
       * @return The msgStatus.
       */
      @java.lang.Override
      public com.whale.generator.netty.common.protocol.Msg.StatusType getMsgStatus() {
        @SuppressWarnings("deprecation")
        com.whale.generator.netty.common.protocol.Msg.StatusType result = com.whale.generator.netty.common.protocol.Msg.StatusType.valueOf(msgStatus_);
        return result == null ? com.whale.generator.netty.common.protocol.Msg.StatusType.ALREADY : result;
      }
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>optional .StatusType msgStatus = 6;</code>
       * @param value The msgStatus to set.
       * @return This builder for chaining.
       */
      public Builder setMsgStatus(com.whale.generator.netty.common.protocol.Msg.StatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        msgStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>optional .StatusType msgStatus = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgStatus() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clusterId_ = "";
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 7;</code>
       * @return Whether the clusterId field is set.
       */
      public boolean hasClusterId() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 7;</code>
       * @return The clusterId.
       */
      public java.lang.String getClusterId() {
        java.lang.Object ref = clusterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clusterId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 7;</code>
       * @return The bytes for clusterId.
       */
      public com.google.protobuf.ByteString
          getClusterIdBytes() {
        java.lang.Object ref = clusterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clusterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 7;</code>
       * @param value The clusterId to set.
       * @return This builder for chaining.
       */
      public Builder setClusterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        clusterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearClusterId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        clusterId_ = getDefaultInstance().getClusterId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 7;</code>
       * @param value The bytes for clusterId to set.
       * @return This builder for chaining.
       */
      public Builder setClusterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        clusterId_ = value;
        onChanged();
        return this;
      }

      private int sendType_ = 0;
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>optional .SendType sendType = 8;</code>
       * @return Whether the sendType field is set.
       */
      @java.lang.Override public boolean hasSendType() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>optional .SendType sendType = 8;</code>
       * @return The sendType.
       */
      @java.lang.Override
      public com.whale.generator.netty.common.protocol.Msg.SendType getSendType() {
        @SuppressWarnings("deprecation")
        com.whale.generator.netty.common.protocol.Msg.SendType result = com.whale.generator.netty.common.protocol.Msg.SendType.valueOf(sendType_);
        return result == null ? com.whale.generator.netty.common.protocol.Msg.SendType.ACCEPTER : result;
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>optional .SendType sendType = 8;</code>
       * @param value The sendType to set.
       * @return This builder for chaining.
       */
      public Builder setSendType(com.whale.generator.netty.common.protocol.Msg.SendType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        sendType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>optional .SendType sendType = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        sendType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sendUserId_ = "";
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 10;</code>
       * @return Whether the sendUserId field is set.
       */
      public boolean hasSendUserId() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 10;</code>
       * @return The sendUserId.
       */
      public java.lang.String getSendUserId() {
        java.lang.Object ref = sendUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sendUserId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 10;</code>
       * @return The bytes for sendUserId.
       */
      public com.google.protobuf.ByteString
          getSendUserIdBytes() {
        java.lang.Object ref = sendUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 10;</code>
       * @param value The sendUserId to set.
       * @return This builder for chaining.
       */
      public Builder setSendUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        sendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendUserId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        sendUserId_ = getDefaultInstance().getSendUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 10;</code>
       * @param value The bytes for sendUserId to set.
       * @return This builder for chaining.
       */
      public Builder setSendUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        sendUserId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 11;</code>
       * @return Whether the token field is set.
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 11;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 11;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 11;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000400);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 11;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Base)
    }

    // @@protoc_insertion_point(class_scope:Base)
    private static final com.whale.generator.netty.common.protocol.Msg.Base DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.whale.generator.netty.common.protocol.Msg.Base();
    }

    public static com.whale.generator.netty.common.protocol.Msg.Base getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Base>
        PARSER = new com.google.protobuf.AbstractParser<Base>() {
      @java.lang.Override
      public Base parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Base(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Base> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Base> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.whale.generator.netty.common.protocol.Msg.Base getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Base_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Base_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\032\rCommand.proto\"\346\001\n\004Base\022" +
      "\016\n\006cMsgId\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\025\n\003cmd\030" +
      "\004 \002(\0162\010.Command\022\022\n\naccepterId\030\005 \001(\t\022\020\n\010s" +
      "endTime\030\t \002(\022\022\r\n\005msgId\030\001 \001(\t\022\036\n\tmsgStatu" +
      "s\030\006 \001(\0162\013.StatusType\022\021\n\tclusterId\030\007 \001(\t\022" +
      "\033\n\010sendType\030\010 \001(\0162\t.SendType\022\022\n\nsendUser" +
      "Id\030\n \001(\t\022\r\n\005token\030\013 \001(\t*%\n\010SendType\022\014\n\010A" +
      "CCEPTER\020\000\022\013\n\007CLUSTER\020\001*;\n\nStatusType\022\013\n\007" +
      "ALREADY\020\000\022\010\n\004READ\020\001\022\n\n\006RECALL\020\002\022\n\n\006REMOV" +
      "E\020\003B0\n)com.whale.generator.netty.common." +
      "protocolB\003Msg"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.whale.generator.netty.common.protocol.Cmd.getDescriptor(),
        });
    internal_static_Base_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Base_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Base_descriptor,
        new java.lang.String[] { "CMsgId", "Content", "Cmd", "AccepterId", "SendTime", "MsgId", "MsgStatus", "ClusterId", "SendType", "SendUserId", "Token", });
    com.whale.generator.netty.common.protocol.Cmd.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
