// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.whale.generator.netty.common.protocol;

public final class MsgBase {
  private MsgBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return Whether the msgId field is set.
     */
    boolean hasMsgId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return The msgId.
     */
    java.lang.String getMsgId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 2;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .CommandType cmd = 3;</code>
     * @return Whether the cmd field is set.
     */
    boolean hasCmd();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .CommandType cmd = 3;</code>
     * @return The cmd.
     */
    com.whale.generator.netty.common.protocol.Command.CommandType getCmd();

    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>optional .StatusType msgStatus = 4;</code>
     * @return Whether the msgStatus field is set.
     */
    boolean hasMsgStatus();
    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>optional .StatusType msgStatus = 4;</code>
     * @return The msgStatus.
     */
    com.whale.generator.netty.common.protocol.MsgStatus.StatusType getMsgStatus();

    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return Whether the accepterId field is set.
     */
    boolean hasAccepterId();
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return The accepterId.
     */
    java.lang.String getAccepterId();
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return The bytes for accepterId.
     */
    com.google.protobuf.ByteString
        getAccepterIdBytes();

    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 6;</code>
     * @return Whether the clusterId field is set.
     */
    boolean hasClusterId();
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 6;</code>
     * @return The clusterId.
     */
    java.lang.String getClusterId();
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 6;</code>
     * @return The bytes for clusterId.
     */
    com.google.protobuf.ByteString
        getClusterIdBytes();

    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>optional .Type sendType = 7;</code>
     * @return Whether the sendType field is set.
     */
    boolean hasSendType();
    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>optional .Type sendType = 7;</code>
     * @return The sendType.
     */
    com.whale.generator.netty.common.protocol.SendType.Type getSendType();

    /**
     * <pre>
     *发送的时间戳
     * </pre>
     *
     * <code>required sint64 sendTime = 8;</code>
     * @return Whether the sendTime field is set.
     */
    boolean hasSendTime();
    /**
     * <pre>
     *发送的时间戳
     * </pre>
     *
     * <code>required sint64 sendTime = 8;</code>
     * @return The sendTime.
     */
    long getSendTime();

    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 9;</code>
     * @return Whether the sendUserId field is set.
     */
    boolean hasSendUserId();
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 9;</code>
     * @return The sendUserId.
     */
    java.lang.String getSendUserId();
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 9;</code>
     * @return The bytes for sendUserId.
     */
    com.google.protobuf.ByteString
        getSendUserIdBytes();

    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 10;</code>
     * @return Whether the token field is set.
     */
    boolean hasToken();
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 10;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 10;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    public Msg() {
      msgId_ = "";
      content_ = "";
      cmd_ = 0;
      msgStatus_ = 0;
      accepterId_ = "";
      clusterId_ = "";
      sendType_ = 0;
      sendUserId_ = "";
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              msgId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              content_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.whale.generator.netty.common.protocol.Command.CommandType value = com.whale.generator.netty.common.protocol.Command.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                cmd_ = rawValue;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.whale.generator.netty.common.protocol.MsgStatus.StatusType value = com.whale.generator.netty.common.protocol.MsgStatus.StatusType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                msgStatus_ = rawValue;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              accepterId_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              clusterId_ = bs;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.whale.generator.netty.common.protocol.SendType.Type value = com.whale.generator.netty.common.protocol.SendType.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                sendType_ = rawValue;
              }
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              sendTime_ = input.readSInt64();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              sendUserId_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              token_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whale.generator.netty.common.protocol.MsgBase.internal_static_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whale.generator.netty.common.protocol.MsgBase.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whale.generator.netty.common.protocol.MsgBase.Msg.class, com.whale.generator.netty.common.protocol.MsgBase.Msg.Builder.class);
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return Whether the msgId field is set.
     */
    @java.lang.Override
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional string msgId = 1;</code>
     * @return The bytes for msgId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 2;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 2;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 3;
    private int cmd_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .CommandType cmd = 3;</code>
     * @return Whether the cmd field is set.
     */
    @java.lang.Override public boolean hasCmd() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .CommandType cmd = 3;</code>
     * @return The cmd.
     */
    @java.lang.Override public com.whale.generator.netty.common.protocol.Command.CommandType getCmd() {
      @SuppressWarnings("deprecation")
      com.whale.generator.netty.common.protocol.Command.CommandType result = com.whale.generator.netty.common.protocol.Command.CommandType.valueOf(cmd_);
      return result == null ? com.whale.generator.netty.common.protocol.Command.CommandType.NORMAL : result;
    }

    public static final int MSGSTATUS_FIELD_NUMBER = 4;
    private int msgStatus_;
    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>optional .StatusType msgStatus = 4;</code>
     * @return Whether the msgStatus field is set.
     */
    @java.lang.Override public boolean hasMsgStatus() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *消息状态改变
     * </pre>
     *
     * <code>optional .StatusType msgStatus = 4;</code>
     * @return The msgStatus.
     */
    @java.lang.Override public com.whale.generator.netty.common.protocol.MsgStatus.StatusType getMsgStatus() {
      @SuppressWarnings("deprecation")
      com.whale.generator.netty.common.protocol.MsgStatus.StatusType result = com.whale.generator.netty.common.protocol.MsgStatus.StatusType.valueOf(msgStatus_);
      return result == null ? com.whale.generator.netty.common.protocol.MsgStatus.StatusType.ALREADY : result;
    }

    public static final int ACCEPTERID_FIELD_NUMBER = 5;
    private volatile java.lang.Object accepterId_;
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return Whether the accepterId field is set.
     */
    @java.lang.Override
    public boolean hasAccepterId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return The accepterId.
     */
    @java.lang.Override
    public java.lang.String getAccepterId() {
      java.lang.Object ref = accepterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accepterId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>optional string accepterId = 5;</code>
     * @return The bytes for accepterId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccepterIdBytes() {
      java.lang.Object ref = accepterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accepterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLUSTERID_FIELD_NUMBER = 6;
    private volatile java.lang.Object clusterId_;
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 6;</code>
     * @return Whether the clusterId field is set.
     */
    @java.lang.Override
    public boolean hasClusterId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 6;</code>
     * @return The clusterId.
     */
    @java.lang.Override
    public java.lang.String getClusterId() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clusterId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 群id
     * </pre>
     *
     * <code>optional string clusterId = 6;</code>
     * @return The bytes for clusterId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClusterIdBytes() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTYPE_FIELD_NUMBER = 7;
    private int sendType_;
    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>optional .Type sendType = 7;</code>
     * @return Whether the sendType field is set.
     */
    @java.lang.Override public boolean hasSendType() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *发送类型
     * </pre>
     *
     * <code>optional .Type sendType = 7;</code>
     * @return The sendType.
     */
    @java.lang.Override public com.whale.generator.netty.common.protocol.SendType.Type getSendType() {
      @SuppressWarnings("deprecation")
      com.whale.generator.netty.common.protocol.SendType.Type result = com.whale.generator.netty.common.protocol.SendType.Type.valueOf(sendType_);
      return result == null ? com.whale.generator.netty.common.protocol.SendType.Type.ACCEPTER : result;
    }

    public static final int SENDTIME_FIELD_NUMBER = 8;
    private long sendTime_;
    /**
     * <pre>
     *发送的时间戳
     * </pre>
     *
     * <code>required sint64 sendTime = 8;</code>
     * @return Whether the sendTime field is set.
     */
    @java.lang.Override
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     *发送的时间戳
     * </pre>
     *
     * <code>required sint64 sendTime = 8;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return sendTime_;
    }

    public static final int SENDUSERID_FIELD_NUMBER = 9;
    private volatile java.lang.Object sendUserId_;
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 9;</code>
     * @return Whether the sendUserId field is set.
     */
    @java.lang.Override
    public boolean hasSendUserId() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 9;</code>
     * @return The sendUserId.
     */
    @java.lang.Override
    public java.lang.String getSendUserId() {
      java.lang.Object ref = sendUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sendUserId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>optional string sendUserId = 9;</code>
     * @return The bytes for sendUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSendUserIdBytes() {
      java.lang.Object ref = sendUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 10;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 10;</code>
     * @return Whether the token field is set.
     */
    @java.lang.Override
    public boolean hasToken() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 10;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *token值
     * </pre>
     *
     * <code>optional string token = 10;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSendTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, cmd_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(4, msgStatus_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, accepterId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, clusterId_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeEnum(7, sendType_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeSInt64(8, sendTime_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sendUserId_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, cmd_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, msgStatus_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, accepterId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, clusterId_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, sendType_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(8, sendTime_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, sendUserId_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.whale.generator.netty.common.protocol.MsgBase.Msg)) {
        return super.equals(obj);
      }
      com.whale.generator.netty.common.protocol.MsgBase.Msg other = (com.whale.generator.netty.common.protocol.MsgBase.Msg) obj;

      if (hasMsgId() != other.hasMsgId()) return false;
      if (hasMsgId()) {
        if (!getMsgId()
            .equals(other.getMsgId())) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasCmd() != other.hasCmd()) return false;
      if (hasCmd()) {
        if (cmd_ != other.cmd_) return false;
      }
      if (hasMsgStatus() != other.hasMsgStatus()) return false;
      if (hasMsgStatus()) {
        if (msgStatus_ != other.msgStatus_) return false;
      }
      if (hasAccepterId() != other.hasAccepterId()) return false;
      if (hasAccepterId()) {
        if (!getAccepterId()
            .equals(other.getAccepterId())) return false;
      }
      if (hasClusterId() != other.hasClusterId()) return false;
      if (hasClusterId()) {
        if (!getClusterId()
            .equals(other.getClusterId())) return false;
      }
      if (hasSendType() != other.hasSendType()) return false;
      if (hasSendType()) {
        if (sendType_ != other.sendType_) return false;
      }
      if (hasSendTime() != other.hasSendTime()) return false;
      if (hasSendTime()) {
        if (getSendTime()
            != other.getSendTime()) return false;
      }
      if (hasSendUserId() != other.hasSendUserId()) return false;
      if (hasSendUserId()) {
        if (!getSendUserId()
            .equals(other.getSendUserId())) return false;
      }
      if (hasToken() != other.hasToken()) return false;
      if (hasToken()) {
        if (!getToken()
            .equals(other.getToken())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgId()) {
        hash = (37 * hash) + MSGID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId().hashCode();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasCmd()) {
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + cmd_;
      }
      if (hasMsgStatus()) {
        hash = (37 * hash) + MSGSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + msgStatus_;
      }
      if (hasAccepterId()) {
        hash = (37 * hash) + ACCEPTERID_FIELD_NUMBER;
        hash = (53 * hash) + getAccepterId().hashCode();
      }
      if (hasClusterId()) {
        hash = (37 * hash) + CLUSTERID_FIELD_NUMBER;
        hash = (53 * hash) + getClusterId().hashCode();
      }
      if (hasSendType()) {
        hash = (37 * hash) + SENDTYPE_FIELD_NUMBER;
        hash = (53 * hash) + sendType_;
      }
      if (hasSendTime()) {
        hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSendTime());
      }
      if (hasSendUserId()) {
        hash = (37 * hash) + SENDUSERID_FIELD_NUMBER;
        hash = (53 * hash) + getSendUserId().hashCode();
      }
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.whale.generator.netty.common.protocol.MsgBase.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.whale.generator.netty.common.protocol.MsgBase.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg)
        com.whale.generator.netty.common.protocol.MsgBase.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whale.generator.netty.common.protocol.MsgBase.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whale.generator.netty.common.protocol.MsgBase.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whale.generator.netty.common.protocol.MsgBase.Msg.class, com.whale.generator.netty.common.protocol.MsgBase.Msg.Builder.class);
      }

      // Construct using com.whale.generator.netty.common.protocol.MsgBase.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        msgStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        accepterId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        clusterId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        sendType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        sendTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        sendUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whale.generator.netty.common.protocol.MsgBase.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      public com.whale.generator.netty.common.protocol.MsgBase.Msg getDefaultInstanceForType() {
        return com.whale.generator.netty.common.protocol.MsgBase.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public com.whale.generator.netty.common.protocol.MsgBase.Msg build() {
        com.whale.generator.netty.common.protocol.MsgBase.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.whale.generator.netty.common.protocol.MsgBase.Msg buildPartial() {
        com.whale.generator.netty.common.protocol.MsgBase.Msg result = new com.whale.generator.netty.common.protocol.MsgBase.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.msgStatus_ = msgStatus_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.accepterId_ = accepterId_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.clusterId_ = clusterId_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.sendType_ = sendType_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.sendTime_ = sendTime_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000100;
        }
        result.sendUserId_ = sendUserId_;
        if (((from_bitField0_ & 0x00000200) != 0)) {
          to_bitField0_ |= 0x00000200;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whale.generator.netty.common.protocol.MsgBase.Msg) {
          return mergeFrom((com.whale.generator.netty.common.protocol.MsgBase.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whale.generator.netty.common.protocol.MsgBase.Msg other) {
        if (other == com.whale.generator.netty.common.protocol.MsgBase.Msg.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000001;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasMsgStatus()) {
          setMsgStatus(other.getMsgStatus());
        }
        if (other.hasAccepterId()) {
          bitField0_ |= 0x00000010;
          accepterId_ = other.accepterId_;
          onChanged();
        }
        if (other.hasClusterId()) {
          bitField0_ |= 0x00000020;
          clusterId_ = other.clusterId_;
          onChanged();
        }
        if (other.hasSendType()) {
          setSendType(other.getSendType());
        }
        if (other.hasSendTime()) {
          setSendTime(other.getSendTime());
        }
        if (other.hasSendUserId()) {
          bitField0_ |= 0x00000100;
          sendUserId_ = other.sendUserId_;
          onChanged();
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000200;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasContent()) {
          return false;
        }
        if (!hasCmd()) {
          return false;
        }
        if (!hasSendTime()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whale.generator.netty.common.protocol.MsgBase.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whale.generator.netty.common.protocol.MsgBase.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msgId_ = "";
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @return Whether the msgId field is set.
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @return The msgId.
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>optional string msgId = 1;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 2;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 2;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      private int cmd_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .CommandType cmd = 3;</code>
       * @return Whether the cmd field is set.
       */
      @java.lang.Override public boolean hasCmd() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .CommandType cmd = 3;</code>
       * @return The cmd.
       */
      @java.lang.Override
      public com.whale.generator.netty.common.protocol.Command.CommandType getCmd() {
        @SuppressWarnings("deprecation")
        com.whale.generator.netty.common.protocol.Command.CommandType result = com.whale.generator.netty.common.protocol.Command.CommandType.valueOf(cmd_);
        return result == null ? com.whale.generator.netty.common.protocol.Command.CommandType.NORMAL : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .CommandType cmd = 3;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(com.whale.generator.netty.common.protocol.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .CommandType cmd = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int msgStatus_ = 0;
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>optional .StatusType msgStatus = 4;</code>
       * @return Whether the msgStatus field is set.
       */
      @java.lang.Override public boolean hasMsgStatus() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>optional .StatusType msgStatus = 4;</code>
       * @return The msgStatus.
       */
      @java.lang.Override
      public com.whale.generator.netty.common.protocol.MsgStatus.StatusType getMsgStatus() {
        @SuppressWarnings("deprecation")
        com.whale.generator.netty.common.protocol.MsgStatus.StatusType result = com.whale.generator.netty.common.protocol.MsgStatus.StatusType.valueOf(msgStatus_);
        return result == null ? com.whale.generator.netty.common.protocol.MsgStatus.StatusType.ALREADY : result;
      }
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>optional .StatusType msgStatus = 4;</code>
       * @param value The msgStatus to set.
       * @return This builder for chaining.
       */
      public Builder setMsgStatus(com.whale.generator.netty.common.protocol.MsgStatus.StatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        msgStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息状态改变
       * </pre>
       *
       * <code>optional .StatusType msgStatus = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        msgStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object accepterId_ = "";
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @return Whether the accepterId field is set.
       */
      public boolean hasAccepterId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @return The accepterId.
       */
      public java.lang.String getAccepterId() {
        java.lang.Object ref = accepterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accepterId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @return The bytes for accepterId.
       */
      public com.google.protobuf.ByteString
          getAccepterIdBytes() {
        java.lang.Object ref = accepterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accepterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @param value The accepterId to set.
       * @return This builder for chaining.
       */
      public Builder setAccepterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        accepterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccepterId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        accepterId_ = getDefaultInstance().getAccepterId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>optional string accepterId = 5;</code>
       * @param value The bytes for accepterId to set.
       * @return This builder for chaining.
       */
      public Builder setAccepterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        accepterId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clusterId_ = "";
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 6;</code>
       * @return Whether the clusterId field is set.
       */
      public boolean hasClusterId() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 6;</code>
       * @return The clusterId.
       */
      public java.lang.String getClusterId() {
        java.lang.Object ref = clusterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clusterId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 6;</code>
       * @return The bytes for clusterId.
       */
      public com.google.protobuf.ByteString
          getClusterIdBytes() {
        java.lang.Object ref = clusterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clusterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 6;</code>
       * @param value The clusterId to set.
       * @return This builder for chaining.
       */
      public Builder setClusterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        clusterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearClusterId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        clusterId_ = getDefaultInstance().getClusterId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群id
       * </pre>
       *
       * <code>optional string clusterId = 6;</code>
       * @param value The bytes for clusterId to set.
       * @return This builder for chaining.
       */
      public Builder setClusterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        clusterId_ = value;
        onChanged();
        return this;
      }

      private int sendType_ = 0;
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>optional .Type sendType = 7;</code>
       * @return Whether the sendType field is set.
       */
      @java.lang.Override public boolean hasSendType() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>optional .Type sendType = 7;</code>
       * @return The sendType.
       */
      @java.lang.Override
      public com.whale.generator.netty.common.protocol.SendType.Type getSendType() {
        @SuppressWarnings("deprecation")
        com.whale.generator.netty.common.protocol.SendType.Type result = com.whale.generator.netty.common.protocol.SendType.Type.valueOf(sendType_);
        return result == null ? com.whale.generator.netty.common.protocol.SendType.Type.ACCEPTER : result;
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>optional .Type sendType = 7;</code>
       * @param value The sendType to set.
       * @return This builder for chaining.
       */
      public Builder setSendType(com.whale.generator.netty.common.protocol.SendType.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        sendType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送类型
       * </pre>
       *
       * <code>optional .Type sendType = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sendType_ = 0;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <pre>
       *发送的时间戳
       * </pre>
       *
       * <code>required sint64 sendTime = 8;</code>
       * @return Whether the sendTime field is set.
       */
      @java.lang.Override
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       *发送的时间戳
       * </pre>
       *
       * <code>required sint64 sendTime = 8;</code>
       * @return The sendTime.
       */
      @java.lang.Override
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <pre>
       *发送的时间戳
       * </pre>
       *
       * <code>required sint64 sendTime = 8;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(long value) {
        bitField0_ |= 0x00000080;
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的时间戳
       * </pre>
       *
       * <code>required sint64 sendTime = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object sendUserId_ = "";
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 9;</code>
       * @return Whether the sendUserId field is set.
       */
      public boolean hasSendUserId() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 9;</code>
       * @return The sendUserId.
       */
      public java.lang.String getSendUserId() {
        java.lang.Object ref = sendUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sendUserId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 9;</code>
       * @return The bytes for sendUserId.
       */
      public com.google.protobuf.ByteString
          getSendUserIdBytes() {
        java.lang.Object ref = sendUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 9;</code>
       * @param value The sendUserId to set.
       * @return This builder for chaining.
       */
      public Builder setSendUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        sendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendUserId() {
        bitField0_ = (bitField0_ & ~0x00000100);
        sendUserId_ = getDefaultInstance().getSendUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>optional string sendUserId = 9;</code>
       * @param value The bytes for sendUserId to set.
       * @return This builder for chaining.
       */
      public Builder setSendUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        sendUserId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 10;</code>
       * @return Whether the token field is set.
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 10;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 10;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 10;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000200);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token值
       * </pre>
       *
       * <code>optional string token = 10;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg)
    }

    // @@protoc_insertion_point(class_scope:Msg)
    private static final com.whale.generator.netty.common.protocol.MsgBase.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.whale.generator.netty.common.protocol.MsgBase.Msg();
    }

    public static com.whale.generator.netty.common.protocol.MsgBase.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.whale.generator.netty.common.protocol.MsgBase.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\032\rCommand.proto\032\017MsgStatu" +
      "s.proto\032\016SendType.proto\"\325\001\n\003Msg\022\r\n\005msgId" +
      "\030\001 \001(\t\022\017\n\007content\030\002 \002(\t\022\031\n\003cmd\030\003 \002(\0162\014.C" +
      "ommandType\022\036\n\tmsgStatus\030\004 \001(\0162\013.StatusTy" +
      "pe\022\022\n\naccepterId\030\005 \001(\t\022\021\n\tclusterId\030\006 \001(" +
      "\t\022\027\n\010sendType\030\007 \001(\0162\005.Type\022\020\n\010sendTime\030\010" +
      " \002(\022\022\022\n\nsendUserId\030\t \001(\t\022\r\n\005token\030\n \001(\tB" +
      "4\n)com.whale.generator.netty.common.prot" +
      "ocolB\007MsgBase"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.whale.generator.netty.common.protocol.Command.getDescriptor(),
          com.whale.generator.netty.common.protocol.MsgStatus.getDescriptor(),
          com.whale.generator.netty.common.protocol.SendType.getDescriptor(),
        });
    internal_static_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_descriptor,
        new java.lang.String[] { "MsgId", "Content", "Cmd", "MsgStatus", "AccepterId", "ClusterId", "SendType", "SendTime", "SendUserId", "Token", });
    com.whale.generator.netty.common.protocol.Command.getDescriptor();
    com.whale.generator.netty.common.protocol.MsgStatus.getDescriptor();
    com.whale.generator.netty.common.protocol.SendType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
