security:
  oauth2:
    resourceId: 2
    resource:
      token-info-uri: http://127.0.0.1:8000/oauth/check_token
      loadBalanced: true
    client:
      client-id: whale
      client-secret: 123456
      access-token-uri: http://127.0.0.1:8000/oauth/token
      user-authorization-uri: http://127.0.0.1:8000/oauth/authorize
      ignore-urls:
        - /v2/api-docs
        - /swagger-resources
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /swagger-ui.html
        - /webjars/**
        - /doc.html
