security:
  oauth2:
    client:
      resourceId: 1
      ignore-urls:
        - /v2/api-docs
        - /swagger-resources
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /swagger-ui.html
        - /webjars/**
