security:
  oauth2:
    resourceId: 2
    resource:
      token-info-uri: http://127.0.0.1:8000/whale-oauth2/oauth/check_token
    client:
      client-id: whale
      client-secret: whale
      access-token-uri: http://127.0.0.1:8000/whale-oauth2/oauth/token
      user-authorization-uri: http://127.0.0.1:8000/whale-oauth2/oauth/authorize
      ignore-urls:
        - /v2/api-docs
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /swagger-ui.html
        - /webjars/**
        - /doc.html
        - /test/**

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 16000
        readTimeout: 16000
dubbo:
  provider:
    filter: -exception
  consumer:
    check: false
  scan:
    # com.whale.api.dubbo 服务扫描基准包
    base-packages: com.whale.business
  application:
    name: ${spring.application.name}
    id: ${spring.application.name}
  registry:
    #挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: -1
    serialization: kryo

  cloud:
    #配置订阅服务多个服务用,隔开,不配置默认订阅注册中心所有服务
    subscribed-services: 'whale-business-order'

logging:
  config: classpath:logback-spring.xml
  level:
    com.whale: debug
