security:
  oauth2:
    resource:
      token-info-uri: http://127.0.0.1:8000/oauth/check_token
    client:
      clientId: whale
      clientSecret: 123456
      accessTokenUri: http://127.0.0.1:8000/oauth/token
      userAuthorizationUri: http://127.0.0.1:8000/oauth/authorize
      tokenName: token
      ignore-urls:
        - /v2/api-docs
        - /swagger-resources
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /swagger-ui.html
        - /webjars/**
        - /doc.html
        - /oauth/**
        - /test2/**


dubbo:
  consumer:
    check: false
  scan:
    # com.whale.api.dubbo 服务扫描基准包
    base-packages: com.whale.oauth2.service
  application:
    name: ${spring.application.name}
    id: ${spring.application.name}
  registry:
    #挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: -1
  cloud:
    #配置订阅服务多个服务用,隔开,不配置默认订阅注册中心所有服务
    subscribed-services: 'whale-business-system'