security:
  oauth2:
    resourceId: 1
    client:
      ignore-urls:
        - /v2/api-docs
        - /swagger-resources
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /swagger-ui.html
        - /webjars/**
        - /doc.html