security:
  oauth2:
    resourceId: 1
    resource:
      token-info-uri: http://127.0.0.1:8000/oauth/check_token
      prefer-token-info: true
    authorization:
      check-token-access: http://127.0.0.1:8000/oauth/check_token
    client:
      clientId: whale
      clientSecret: whale
      accessTokenUri: http://127.0.0.1:8000/oauth/token
      user-authorization-uri: http://127.0.0.1:8000/oauth/authorize
      ignore-urls:
        - /v2/api-docs
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /swagger-ui.html
        - /webjars/**
        - /doc.html
        - /test/**


logging:
  config: classpath:logback-spring.xml
