spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: whale-oauth2
          uri: lb://whale-oauth2
          order: 0
          predicates:
            - Path=/oauth2/**
          filters:
            - StripPrefix=1
        - id: whale-business-system
          uri: lb://business-system
          order: 0
          predicates:
            - Path=/business-system/**
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: debug


