spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: business-social
          uri: lb://business-social
          order: 0
          predicates:
            - Path=/business-social/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 9999
#      scg:
#        fallback:
#          mode: response
#          response-status: 455
#          response-body: error!
      # 服务启动直接建立心跳连接
      #eager: true
# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug
#server:
#  port: 9010

