## ElasticSearch - start
# 开启 Elasticsearch 仓库(默认值:true)
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.5.58:9300
      properties:
        transport:
          tcp:
            connect_timeout=120s:
  # 默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
  # spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300
spring.data.elasticsearch.cluster-nodes=192.168.5.58:9300
  # 集群名(默认值: elasticsearch)
spring.data.elasticsearch.cluster-name=realestate
  # 集群节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点
  #spring.data.elasticsearch.propertie 用来配置客户端的额外属性
  # 存储索引的位置
spring.data.elasticsearch.properties.path.home=/data/project/target/elastic
  # 连接超时的时间
spring.data.elasticsearch.
